language: dart

# We currently are building against the Dart2 SDK.
dart:
  - dev

# Gives more resources on Travis (8GB Ram, 2CPUs).
# Do not remove without verifying w/ Travis.
sudo: required

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

# Build stages: https://docs.travis-ci.com/user/build-stages/.
stages:
  - presubmit
  - building
  - testing

jobs:
  - stage: presubmit
    script: ./tool/travis.sh analyze
    env: PKG="example/coffee"
  - stage: presubmit
    script: ./tool/travis.sh analyze
    env: PKG="example/train"
  - stage: presubmit
    script: ./tool/travis.sh analyze
    env: PKG="package/inject"
  - stage: presubmit
    script: ./tool/travis.sh analyze
    env: PKG="package/inject_generator"

  # TODO: Add build, test phases.
